name: mapdn
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - argon2-cffi=20.1.0=py37h8f50634_2
  - async_generator=1.10=py_0
  - attrs=20.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=1.0=mkl
  - bleach=3.2.1=pyh9f0ad1d_0
  - brotlipy=0.7.0=py37hb5d75c8_1001
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py37he5f6b98_2
  - cffi=1.14.3=py37he30daa8_0
  - chardet=3.0.4=py37he5f6b98_1008
  - cryptography=3.1.1=py37hff6837a_1
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37hc8dfbb8_1002
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - intel-openmp=2020.2=254
  - ipython_genutils=0.2.0=py_1
  - jinja2=2.11.2=pyh9f0ad1d_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.6.3=py37hc8dfbb8_2
  - jupyterlab=2.2.8=py_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=1.2.0=py_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libsodium=1.0.18=h516909a_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - llvmlite=0.34.0=py37h269e1b5_4
  - markupsafe=1.1.1=py37hb5d75c8_2
  - mistune=0.8.4=py37h8f50634_1002
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.2.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py37hc8dfbb8_1
  - nbformat=5.0.8=py_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.4.1=py_0
  - notebook=6.1.4=py37hc8dfbb8_1
  - numba=0.51.2=py37h04863e7_1
  - openssl=1.1.1h=h516909a_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandoc=2.11.0.2=hd18ef5c_0
  - pandocfilters=1.4.2=py_1
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt_toolkit=1.0.15=py_1
  - pycparser=2.20=pyh9f0ad1d_2
  - pyopenssl=19.1.0=py_1
  - pyrsistent=0.17.3=py37h8f50634_1
  - pysocks=1.7.1=py37he5f6b98_2
  - python=3.7.9=h7579374_0
  - python_abi=3.7=1_cp37m
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=pyh9f0ad1d_0
  - send2trash=1.5.0=py_0
  - simplegeneric=0.8.1=py_1
  - sqlite=3.33.0=h62c20be_0
  - tbb=2020.3=hfd86e86_0
  - terminado=0.9.1=py37hc8dfbb8_1
  - testpath=0.4.4=py_0
  - tk=8.6.10=hbc83047_0
  - urllib3=1.25.11=py_0
  - webencodings=0.5.1=py_1
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.3=he1b5a44_2
  - zipp=3.3.1=py_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.10.0
    - astor==0.8.1
    - astunparse==1.6.3
    - atari-py
    - backcall==0.2.0
    - cachetools==4.1.1
    - cloudpickle==1.2.2
    - colorama==0.4.4
    - crc32c==2.2
    - cycler==0.10.0
    - dataclasses==0.6
    - decorator==4.4.2
    - docopt==0.6.2
    - docutils==0.16
    - et-xmlfile==1.1.0
    - flatbuffers==1.12
    - gast==0.2.2
    - gitdb==4.0.7
    - gitpython==3.1.14
    - google-auth==1.22.1
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - gym
    - h5py==2.10.0
    - ipykernel==5.3.4
    - ipython==7.18.1
    - ipython-genutils==0.2.0
    - jedi==0.17.2
    - joblib==0.17.0
    - jsonpickle==1.5.2
    - jupyter-client==6.1.7
    - jupyter-core==4.6.3
    - kaleido==0.2.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.2.0
    - markdown==3.3.2
    - matplotlib==2.2.5
    - metakernel==0.27.0
    - mpi4py==3.0.3
    - munch==2.5.0
    - networkx==2.5
    - numpy==1.19.5
    - numpy-stl==2.16.0
    - oauthlib==3.1.0
    - oct2py==4.0.6
    - octave-kernel==0.32.0
    - opencv-python==4.4.0.44
    - openpyxl==3.0.7
    - opt-einsum==3.3.0
    - pandapower==2.7.0
    - pandas==1.1.3
    - parso==0.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.0.1
    - pip==21.2.4
    - plotly==5.3.1
    - prompt-toolkit==3.0.8
    - protobuf==3.13.0
    - ptyprocess==0.6.0
    - py-cpuinfo==8.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygame==1.9.6
    - pyglet==2.0.dev0
    - pygments==2.7.1
    - pyparsing==3.0.0a2
    - pypower==5.1.4
    - python-dateutil==2.8.1
    - python-igraph==0.9.6
    - python-utils==2.5.6
    - pytz==2020.1
    - pyzmq==19.0.2
    - recommonmark==0.4.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - sacred==0.8.2
    - scipy==1.4.1
    - setuptools==50.3.2
    - six==1.15.0
    - smmap==4.0.0
    - soundfile==0.10.3.post1
    - stable-baselines==2.10.1
    - tenacity==8.0.1
    - tensorboard==2.1.1
    - tensorboard-data-server==0.6.0
    - tensorboard-plugin-wit==1.7.0
    - tensorboardx==2.2
    - tensorflow==2.1.0
    - tensorflow-estimator==2.1.0
    - termcolor==1.1.0
    - texttable==1.6.4
    - torch==1.8.1
    - tornado==6.1b1
    - traitlets==5.0.5
    - typing-extensions==3.7.4.3
    - wcwidth==0.2.5
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - xlrd==1.2.0
    - xlsxwriter==1.3.7
    - PyYAML

